version: '3.7'
services:
  app:
    container_name: echo
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./start.sh"]
    # need $ chmod +x start.sh

  test_mysql:
    platform: 'linux/amd64'
    image: mysql:5.7
    container_name: mysql
    volumes:
      - go_mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: 'Asia/Tokyo'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
volumes:
  go_mysql_data: